project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Seminar 2"
  favicon: "plot/seminar-2-hex-logo.png"
  
  repo-url: https://github.com/seminar-academic-writing/class-2024
  site-url: https://seminar-academic-writing.github.io/class-2024/
  
  sidebar:
    style: docked
    pinned: true
    seacrh: true
    logo: "plot/seminar-2-hex-logo.png"
    contents:
      - href: "01-course-outline.qmd"
        text: "Course Outline"
      - section: "Class materials"
        contents:
          - href: "02-week12-foundation.qmd"
            text: "W12: Foundation of academic writing"
          - href: "03-week34-dev-research-methods.qmd"
            text: "W34: Developing research methods"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

